

# ONNX 模型路径 (当 model_type 为 'onnx' 时使用)
onnx_path: "policyallref.onnx"

# 参考动作文件路径 (相对于MotionTracking目录)
motion_file: "command/sfu_29dof.pkl"

# 选择第几个动作（从0开始，默认第一个动作）
motion_index: 0

# motion_length 会自动从动作文件读取，这里仅作为备用
motion_length: 17.433

kps: [100, 100, 100, 200, 20, 20,
            100, 100, 100, 200, 20, 20,
            400, 400, 400,
            90,   60,  20, 60, 20, 20, 20,
            90,   60,  20, 60, 20, 20, 20
            ]

kds: [2.5, 2.5, 2.5, 5.0, 0.2, 0.1,
            2.5, 2.5, 2.5, 5.0, 0.2, 0.1,
            5.0, 5.0, 5.0,
            2.0, 1.0, 0.4, 1.0, 0.4, 0.4, 0.4,
            2.0, 1.0, 0.4, 1.0, 0.4, 0.4, 0.4
            ]

tau_limit: [88, 88, 88, 139, 50, 50,
            88, 88, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 5, 5, 5,
            25, 25, 25, 25, 5, 5, 5
           ]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                 -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
                  ]

dof23_index: [ 0, 1, 2, 3, 4, 5,
               6, 7, 8 ,9 ,10, 11,
               12, 13, 14,
               15, 16, 17, 18,
               22, 23, 24, 25
             ]

ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.5

history_length: 1
num_actions: 19
num_obs_robot: 123
num_obs_ref_motion: 120
num_obs_priv: 40