

# ONNX 模型路径 (当 model_type 为 'onnx' 时使用)
onnx_path: "policy-12-12_19-48.onnx"

# 参考动作文件路径 (相对于MotionTracking目录)
motion_file: "command/sfu_29dof.pkl"

# 选择第几个动作（从0开始，默认第一个动作）
motion_index: 0

# motion_length 会自动从动作文件读取，这里仅作为备用
motion_length: 17.433

kps: [40.179237365722656, 99.09842681884766, 
  40.179237365722656, 99.09842681884766, 
  28.501245498657227, 28.501245498657227, 
  40.179237365722656, 99.09842681884766, 
  40.179237365722656, 99.09842681884766, 
  28.501245498657227, 28.501245498657227, 
  40.179237365722656, 28.501245498657227, 
  28.501245498657227, 14.250622749328613, 
  14.250622749328613, 14.250622749328613, 
  14.250622749328613, 14.250622749328613, 
  16.77832794189453, 16.77832794189453, 
  14.250622749328613, 14.250622749328613, 
  14.250622749328613, 14.250622749328613, 
  14.250622749328613, 16.77832794189453, 16.77832794189453
            ]

kds: [2.557889699935913, 6.308801651000977, 2.557889699935913, 
  6.308801651000977, 1.8144457340240479, 1.8144457340240479,
   2.557889699935913, 6.308801651000977, 2.557889699935913,
    6.308801651000977, 1.8144457340240479, 1.8144457340240479,
     2.557889699935913, 1.8144457340240479, 1.8144457340240479,
      0.9072228670120239, 0.9072228670120239, 0.9072228670120239,
       0.9072228670120239, 0.9072228670120239, 1.0681414604187012,
        1.0681414604187012, 0.9072228670120239, 0.9072228670120239,
         0.9072228670120239, 0.9072228670120239, 0.9072228670120239,
          1.0681414604187012, 1.0681414604187012]

tau_limit: [88, 88, 88, 139, 50, 50,
            88, 88, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 5, 5, 5,
            25, 25, 25, 25, 5, 5, 5
           ]

default_angles: [-0.312,  0.0,  0.0,  0.669, -0.363, 0.0, 
                 -0.312,  0.0,  0.0,  0.669, -0.363, 0.0,
                  0.0, 0.0, 0.0,
                  0.2, 0.2, 0.0, 0.6, 0.0, 0.0, 0.0, 
                  0.2, -0.2, 0.0, 0.6, 0.0, 0.0, 0.0
                  ]

dof23_index: [ 0, 1, 2, 3, 4, 5,
               6, 7, 8 ,9 ,10, 11,
               12, 13, 14,
               15, 16, 17, 18,
               22, 23, 24, 25
             ]

ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.5

history_length: 1
num_actions: 19
num_obs_robot: 123
num_obs_ref_motion: 120
num_obs_priv: 40